INSERT INTO MESSAGE VALUES('Mustafa', 'Emily I want to thank you for everything you have done for me, without you I would not be in the position to have a new career path and bright future ahead of me.');
INSERT INTO MESSAGE VALUES('Wilber', 'Thank you for the knowledge you have bestowed upon us. It will not go to waste.');
INSERT INTO MESSAGE VALUES('Toby', 'Thank you, Emily. You have been an amazing mentor and your passion is infectious!');
INSERT INTO MESSAGE VALUES('Jolie', 'Thank you for your understanding, encouragement, and belief in us! =D');
INSERT INTO MESSAGE VALUES('Ben M.', 'Thank you for instructing me in the mystic arts of software development. I owe my hat to you.');
INSERT INTO MESSAGE VALUES('Dylan', 'Many thanks for sharing your knowledge and experience.');
INSERT INTO MESSAGE VALUES('Richard', 'Thank you for the future that you have given me.');
INSERT INTO MESSAGE VALUES('Adam', 'Thank you for performing a difficult job. We appreciate the effort you put in.');
INSERT INTO MESSAGE VALUES('Alphonse', 'Thank you for being a great instructor, I learned a lot.');
INSERT INTO MESSAGE VALUES('Ben W.', 'public class ThankYouEmily{ public static void main(String[] args) { while(true) { System.out.println("Thank You Emily!"); } } }');
INSERT INTO MESSAGE VALUES('Ricardo', 'Thanks for being one amazing Instructor Emily! And for laughing at my lame jokes :D. Gonna miss ya!');
INSERT INTO MESSAGE VALUES('Shyam', 'Thank you for all of your time and energy!');
INSERT INTO MESSAGE VALUES('Travis', 'Thank you for all the knowledge you imparted on us, for making this stressful experience more enjoyable with your keen sense of humor. We appreciate you!');
INSERT INTO MESSAGE VALUES('Hector', 'Thank you for training me.');
INSERT INTO MESSAGE VALUES('YunHa', 'Thank you, Emily, for all you have done for us!');
INSERT INTO MESSAGE VALUES('Matt', 'Thank you for this incredible journey. I have learned more in the past couple months than the last couple years. You are an incredible teacher.');
INSERT INTO MESSAGE VALUES('Cody', 'Thank you for saving me from PEGA.');
INSERT INTO MESSAGE VALUES('Ed', 'You have been a great instructor, thank you for your patience!');